version: '3'
services:
  frontend:
    build: 
      context: ../
      dockerfile: .Docker/Dockerfile
    image: frontend
    container_name: patrebna_frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../certs:/etc/letsencrypt

  nextjs:
    image: node:latest
    working_dir: /usr/src/app
    command: npm run start 
    volumes:
      - ../:/usr/src/app
    environment:
      - NODE_ENV=production
    depends_on:
      - frontend
    expose:
      - 3000

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    volumes:
      - ../certs:/etc/letsencrypt 
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"