version: '3.4'
services:
  nginx:
    build: 
      context: ../
      dockerfile: .Docker/nginx/Dockerfile
    image: nginx_server
    container_name: patrebna_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../certs:/etc/letsencrypt
    networks:
      - patrebna-network
    depends_on:
      - patrebna_frontend

  next:
    build:
      context: ../
      dockerfile: .Docker/next/Dockerfile
    image: nextjs
    container_name: patrebna_frontend
    restart: always
    environment:
      - NODE_ENV=production
    expose:
      - 3000  
    networks:
      - patrebna-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      retries: 5
      start_period: 5s
      timeout: 5s

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    volumes:
      - ../certs:/etc/letsencrypt 
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - patrebna-network  

networks:
  patrebna-network:
    driver: bridge