version: '3'
services:
  nginx_server:
    build:
      context: ../
      dockerfile: .Docker/nginx/Dockerfile
    image: nginx_server
    container_name: patrebna_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../certs:/etc/letsencrypt
    networks:
      - patrebna-network
  nextjs:
    build:
      context: ../
      dockerfile: .Docker/next/Dockerfile
    image: nextjs
    container_name: patrebna_frontend
    restart: always
    networks:
      - patrebna-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    volumes:
      - ../certs:/etc/letsencrypt
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - patrebna-network
networks:
  patrebna-network:
    driver: bridge
